// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5yhWWDntMngTq0QAebAxqOuxFFAO_a0',
    appId: '1:1074386972595:web:268fd320d4d4d3935625c6',
    messagingSenderId: '1074386972595',
    projectId: 'cashwise-tcc',
    authDomain: 'cashwise-tcc.firebaseapp.com',
    storageBucket: 'cashwise-tcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyykJX2DvNUhB69E-BWWPM31l6Nyd_c-k',
    appId: '1:1074386972595:android:67ee1c032b57757d5625c6',
    messagingSenderId: '1074386972595',
    projectId: 'cashwise-tcc',
    storageBucket: 'cashwise-tcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDR8JbhFykyTR6_78EamLfgb-HCe4NJjM',
    appId: '1:1074386972595:ios:30d873edc26edfac5625c6',
    messagingSenderId: '1074386972595',
    projectId: 'cashwise-tcc',
    storageBucket: 'cashwise-tcc.firebasestorage.app',
    iosClientId: '1074386972595-462oldteael3uj06309gfms8v4iqi3tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDR8JbhFykyTR6_78EamLfgb-HCe4NJjM',
    appId: '1:1074386972595:ios:30d873edc26edfac5625c6',
    messagingSenderId: '1074386972595',
    projectId: 'cashwise-tcc',
    storageBucket: 'cashwise-tcc.firebasestorage.app',
    iosClientId: '1074386972595-462oldteael3uj06309gfms8v4iqi3tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_5yhWWDntMngTq0QAebAxqOuxFFAO_a0',
    appId: '1:1074386972595:web:969916c2148be6565625c6',
    messagingSenderId: '1074386972595',
    projectId: 'cashwise-tcc',
    authDomain: 'cashwise-tcc.firebaseapp.com',
    storageBucket: 'cashwise-tcc.firebasestorage.app',
  );

}